### ISSUE TITLE
M2Cryto python module missing from python virtual env

### ISSUE THREAD

**Issue by buzzzo** [VultureProject/vulture3-gui#18]

**Comment by underscoredje** [comment]
This issue has the same cause than #10.

You can use this as workaround:
```
ln -s /usr/local/lib/libffi.so.7 /usr/local/lib/libffi.so.6
```

**Comment by buzzzo** [comment]
I've already the symlink in place so is not the problem.
Problem is that in the new python virtual env installed by the last update lack the M2Crypto python module.
I've manually copied the M2Crypto dir from the old env (yes , i've backupped it before upgrade) and it works.
