### ISSUE TITLE
1.76 - no css after update

### ISSUE THREAD

**Issue by Skouat** [VultureProject/vulture3-gui#2]
Hi there,

After updating GUI from 1.75 to 1.76, the UI is broken.

With dev tools, I can see that all static files (css, js...) are not found
![image](https://user-images.githubusercontent.com/416780/84412189-2ac10080-ac0f-11ea-9b7e-093862bbaad4.png)

Maybe this is due to the exclusion of the directory `dist` on the [.gitignore](https://github.com/VultureProject/vulture3-gui/blob/v1.76/.gitignore#L36)

**Comment by KGuillemot** [comment]
Hi @Skouat,
Thank you for reporting us that omission.
The fix has been released in version 1.761 (see #3)
Closing this issue
Regards,
Kevin
